name: sscd

dependencies:
  - python==3.7
  # - pip
  - Pillow
  - tqdm
  - jupyterlab
  # - matplotlib
  # - opencv
  # - pip:
    # - Pillow
    # - tensorflow==2.1.0rc1
    # - lxml
    # - tqdm
    # - -e .
